version: "2"
issues:
  fix: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - wsl
    - noinlineerr
  settings:
    cyclop:
      max-complexity: 20
formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt
    - golines
  settings:
    goimports:
      local-prefixes:
        - go.augendre.info/fatcontext
