repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: system
        types_or: [go]
        pass_filenames: false
        entry: mise run lint
      - id: go-test
        name: go test ./...
        language: system
        types_or: [go]
        pass_filenames: false
        entry: mise run test
